---
- name: Install Apache
  hosts: all
  become: yes

  tasks:
  - name: Set fact for RedHat
    ansible.builtin.set_fact:
      service: "httpd"
    when: ansible_facts['os_family'] == "RedHat"

  - name: Set fact for Debian
    ansible.builtin.set_fact:
      service: "apache2"
    when: ansible_facts['os_family'] == "Debian"

  - name: Install Apache WebServer On CentOS
    ansible.builtin.yum:
      name: httpd
      state: present
    when: ansible_facts['os_family'] == "RedHat"
  
  - name: Install Apache WebServer On Ubuntu
    ansible.builtin.apt:
      name: apache2
      state: present
    when: ansible_facts['os_family'] == "Debian"
 
  - name: Get System Uptime
    ansible.builtin.shell: 
      cmd: "/usr/bin/awk '{print $1}' /proc/uptime"
    register: system_uptime

  - name: Put System Uptime In Apache Index File
    ansible.builtin.shell:
      cmd: "/bin/echo System is running since {{ system_uptime.stdout }} seconds > /var/www/html/index.html"

  - name: Start and Enable Apache service
    ansible.builtin.service:
      name: "{{ service }}"
      state: started
      enabled: yes
  
  - name: Check that website returns a status 200 and fail if the word System is not in the page contents
    ansible.builtin.uri:
      url: http://localhost
      return_content: yes
    ignore_errors: yes
    register: this
    failed_when: "'System is running' not in this.content"
      
  - name: Change Apache Port to 8080 On CentOS Machine
    ansible.builtin.replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: '80'
      replace: '8080'
    #ansible.builtin.shell:
    #  cmd: "/usr/bin/sed -i 's/80/8080/g' /etc/httpd/conf/httpd.conf"
    notify:
      - Restart Apache Server
    when: ansible_facts['os_family'] == "RedHat"

  - name: Setup Basic Auth on Ubuntu 
    htpasswd:
      path: /etc/apache2/.htpasswd
      name: user1
      password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33343166633635666330653139663266386631346632373731306537646263393566363431303061
          6534396337363731616431653833663239623664643338650a623563643436666432663436393038
          63613337306562323230343439653534383931363535386465313839336236656232306134393134
          3661343234366666610a356665396133353162633430313439383130326637333266333039653735
          6639
      owner: www-data
      group: www-data
      mode: 0640
    when: ansible_facts['os_family'] == "Debian"

  - name: Copy default conf on Ubuntu
    ansible.builtin.copy:
      src:  000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf
      owner: root
      group: root
      mode: '0644'
    when: ansible_facts['os_family'] == "Debian"
    notify:
      - Restart Apache Server
  
  handlers:
  - name: Restart Apache Server
    ansible.builtin.service:
      name: "{{ service }}"
      state: restarted
    ignore_errors: yes
